"""Add on ice corsi for and against

Revision ID: 36fe5a1e34f7
Revises: c8efec4ac657
Create Date: 2024-10-19 21:53:49.369387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fe5a1e34f7'
down_revision = 'c8efec4ac657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('even_on_ice_corsi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pp_on_ice_corsi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('even_on_ice_against_corsi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pp_on_ice_against_corsi', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game', schema=None) as batch_op:
        batch_op.drop_column('pp_on_ice_against_corsi')
        batch_op.drop_column('even_on_ice_against_corsi')
        batch_op.drop_column('pp_on_ice_corsi')
        batch_op.drop_column('even_on_ice_corsi')

    # ### end Alembic commands ###
