"""Correct goaliegame error

Revision ID: 50182e3180b4
Revises: 36fe5a1e34f7
Create Date: 2024-10-20 10:50:27.000091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50182e3180b4'
down_revision = '36fe5a1e34f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goalie_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('penalty_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goalie_game', schema=None) as batch_op:
        batch_op.drop_column('penalty_minutes')
        batch_op.drop_column('minutes')

    # ### end Alembic commands ###
