"""Add date to final bet

Revision ID: 5851cc150188
Revises: 4a600161b2cc
Create Date: 2024-10-29 21:05:49.661463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5851cc150188'
down_revision = '4a600161b2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_bet', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
