"""Update with hockey stats and add goalies

Revision ID: c8efec4ac657
Revises: 047dd4e4e32a
Create Date: 2024-10-19 20:23:03.915074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8efec4ac657'
down_revision = '047dd4e4e32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goalie_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('goalie_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_goalie_game_game_id_game')),
    sa.ForeignKeyConstraint(['goalie_id'], ['goalie.id'], name=op.f('fk_goalie_game_goalie_id_goalie')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_total_corsi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_total_corsi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_total_hits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_total_hits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_total_blocks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_total_blocks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_pp_corsi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_pp_corsi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_pp_hits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_pp_hits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_pp_blocks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_pp_blocks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_penalty_mins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_penalty_mins', sa.Integer(), nullable=True))

    with op.batch_alter_table('player_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pp_goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pp_assists', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('penalty_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pp_corsi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('even_corsi', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('even_hits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pp_blocks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('even_blocks', sa.Integer(), nullable=True))
        batch_op.alter_column('minutes',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game', schema=None) as batch_op:
        batch_op.alter_column('minutes',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('even_blocks')
        batch_op.drop_column('pp_blocks')
        batch_op.drop_column('even_hits')
        batch_op.drop_column('even_corsi')
        batch_op.drop_column('pp_corsi')
        batch_op.drop_column('penalty_minutes')
        batch_op.drop_column('pp_assists')
        batch_op.drop_column('pp_goals')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('home_penalty_mins')
        batch_op.drop_column('away_penalty_mins')
        batch_op.drop_column('away_pp_blocks')
        batch_op.drop_column('home_pp_blocks')
        batch_op.drop_column('away_pp_hits')
        batch_op.drop_column('home_pp_hits')
        batch_op.drop_column('away_pp_corsi')
        batch_op.drop_column('home_pp_corsi')
        batch_op.drop_column('away_total_blocks')
        batch_op.drop_column('home_total_blocks')
        batch_op.drop_column('away_total_hits')
        batch_op.drop_column('home_total_hits')
        batch_op.drop_column('away_total_corsi')
        batch_op.drop_column('home_total_corsi')

    op.drop_table('goalie_game')
    op.drop_table('goalie')
    # ### end Alembic commands ###
