"""Add shot_stdev

Revision ID: cfeade2a86a6
Revises: 3cc0158ab16a
Create Date: 2024-11-01 01:33:37.429622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfeade2a86a6'
down_revision = '3cc0158ab16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shot_stdev', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game', schema=None) as batch_op:
        batch_op.drop_column('shot_stdev')

    # ### end Alembic commands ###
